<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    public function run()
    {
        $paises = [
            // 🌍 África (54)
            ['nombre' => 'Angola', 'codigo_iso_2' => 'AO', 'codigo_iso_3' => 'AGO'],
            ['nombre' => 'Argelia', 'codigo_iso_2' => 'DZ', 'codigo_iso_3' => 'DZA'],
            ['nombre' => 'Benín', 'codigo_iso_2' => 'BJ', 'codigo_iso_3' => 'BEN'],
            ['nombre' => 'Botsuana', 'codigo_iso_2' => 'BW', 'codigo_iso_3' => 'BWA'],
            ['nombre' => 'Burkina Faso', 'codigo_iso_2' => 'BF', 'codigo_iso_3' => 'BFA'],
            ['nombre' => 'Burundi', 'codigo_iso_2' => 'BI', 'codigo_iso_3' => 'BDI'],
            ['nombre' => 'Cabo Verde', 'codigo_iso_2' => 'CV', 'codigo_iso_3' => 'CPV'],
            ['nombre' => 'Camerún', 'codigo_iso_2' => 'CM', 'codigo_iso_3' => 'CMR'],
            ['nombre' => 'Chad', 'codigo_iso_2' => 'TD', 'codigo_iso_3' => 'TCD'],
            ['nombre' => 'Comoras', 'codigo_iso_2' => 'KM', 'codigo_iso_3' => 'COM'],
            ['nombre' => 'Costa de Marfil', 'codigo_iso_2' => 'CI', 'codigo_iso_3' => 'CIV'],
            ['nombre' => 'Egipto', 'codigo_iso_2' => 'EG', 'codigo_iso_3' => 'EGY'],
            ['nombre' => 'Eritrea', 'codigo_iso_2' => 'ER', 'codigo_iso_3' => 'ERI'],
            ['nombre' => 'Esuatini', 'codigo_iso_2' => 'SZ', 'codigo_iso_3' => 'SWZ'],
            ['nombre' => 'Etiopía', 'codigo_iso_2' => 'ET', 'codigo_iso_3' => 'ETH'],
            ['nombre' => 'Gabón', 'codigo_iso_2' => 'GA', 'codigo_iso_3' => 'GAB'],
            ['nombre' => 'Gambia', 'codigo_iso_2' => 'GM', 'codigo_iso_3' => 'GMB'],
            ['nombre' => 'Ghana', 'codigo_iso_2' => 'GH', 'codigo_iso_3' => 'GHA'],
            ['nombre' => 'Guinea', 'codigo_iso_2' => 'GN', 'codigo_iso_3' => 'GIN'],
            ['nombre' => 'Guinea-Bisáu', 'codigo_iso_2' => 'GW', 'codigo_iso_3' => 'GNB'],
            ['nombre' => 'Guinea Ecuatorial', 'codigo_iso_2' => 'GQ', 'codigo_iso_3' => 'GNQ'],
            ['nombre' => 'Kenia', 'codigo_iso_2' => 'KE', 'codigo_iso_3' => 'KEN'],
            ['nombre' => 'Lesoto', 'codigo_iso_2' => 'LS', 'codigo_iso_3' => 'LSO'],
            ['nombre' => 'Liberia', 'codigo_iso_2' => 'LR', 'codigo_iso_3' => 'LBR'],
            ['nombre' => 'Libia', 'codigo_iso_2' => 'LY', 'codigo_iso_3' => 'LBY'],
            ['nombre' => 'Madagascar', 'codigo_iso_2' => 'MG', 'codigo_iso_3' => 'MDG'],
            ['nombre' => 'Malaui', 'codigo_iso_2' => 'MW', 'codigo_iso_3' => 'MWI'],
            ['nombre' => 'Malí', 'codigo_iso_2' => 'ML', 'codigo_iso_3' => 'MLI'],
            ['nombre' => 'Marruecos', 'codigo_iso_2' => 'MA', 'codigo_iso_3' => 'MAR'],
            ['nombre' => 'Mauricio', 'codigo_iso_2' => 'MU', 'codigo_iso_3' => 'MUS'],
            ['nombre' => 'Mauritania', 'codigo_iso_2' => 'MR', 'codigo_iso_3' => 'MRT'],
            ['nombre' => 'Mozambique', 'codigo_iso_2' => 'MZ', 'codigo_iso_3' => 'MOZ'],
            ['nombre' => 'Namibia', 'codigo_iso_2' => 'NA', 'codigo_iso_3' => 'NAM'],
            ['nombre' => 'Níger', 'codigo_iso_2' => 'NE', 'codigo_iso_3' => 'NER'],
            ['nombre' => 'Nigeria', 'codigo_iso_2' => 'NG', 'codigo_iso_3' => 'NGA'],
            ['nombre' => 'República Centroafricana', 'codigo_iso_2' => 'CF', 'codigo_iso_3' => 'CAF'],
            ['nombre' => 'República del Congo', 'codigo_iso_2' => 'CG', 'codigo_iso_3' => 'COG'],
            ['nombre' => 'República Democrática del Congo', 'codigo_iso_2' => 'CD', 'codigo_iso_3' => 'COD'],
            ['nombre' => 'Ruanda', 'codigo_iso_2' => 'RW', 'codigo_iso_3' => 'RWA'],
            ['nombre' => 'Santo Tomé y Príncipe', 'codigo_iso_2' => 'ST', 'codigo_iso_3' => 'STP'],
            ['nombre' => 'Senegal', 'codigo_iso_2' => 'SN', 'codigo_iso_3' => 'SEN'],
            ['nombre' => 'Seychelles', 'codigo_iso_2' => 'SC', 'codigo_iso_3' => 'SYC'],
            ['nombre' => 'Sierra Leona', 'codigo_iso_2' => 'SL', 'codigo_iso_3' => 'SLE'],
            ['nombre' => 'Somalia', 'codigo_iso_2' => 'SO', 'codigo_iso_3' => 'SOM'],
            ['nombre' => 'Sudáfrica', 'codigo_iso_2' => 'ZA', 'codigo_iso_3' => 'ZAF'],
            ['nombre' => 'Sudán', 'codigo_iso_2' => 'SD', 'codigo_iso_3' => 'SDN'],
            ['nombre' => 'Sudán del Sur', 'codigo_iso_2' => 'SS', 'codigo_iso_3' => 'SSD'],
            ['nombre' => 'Tanzania', 'codigo_iso_2' => 'TZ', 'codigo_iso_3' => 'TZA'],
            ['nombre' => 'Togo', 'codigo_iso_2' => 'TG', 'codigo_iso_3' => 'TGO'],
            ['nombre' => 'Túnez', 'codigo_iso_2' => 'TN', 'codigo_iso_3' => 'TUN'],
            ['nombre' => 'Uganda', 'codigo_iso_2' => 'UG', 'codigo_iso_3' => 'UGA'],
            ['nombre' => 'Yibuti', 'codigo_iso_2' => 'DJ', 'codigo_iso_3' => 'DJI'],
            ['nombre' => 'Zambia', 'codigo_iso_2' => 'ZM', 'codigo_iso_3' => 'ZMB'],
            ['nombre' => 'Zimbabue', 'codigo_iso_2' => 'ZW', 'codigo_iso_3' => 'ZWE'],

            // 🌏 Asia (48)
            ['nombre' => 'Afganistán', 'codigo_iso_2' => 'AF', 'codigo_iso_3' => 'AFG'],
            ['nombre' => 'Arabia Saudita', 'codigo_iso_2' => 'SA', 'codigo_iso_3' => 'SAU'],
            ['nombre' => 'Armenia', 'codigo_iso_2' => 'AM', 'codigo_iso_3' => 'ARM'],
            ['nombre' => 'Azerbaiyán', 'codigo_iso_2' => 'AZ', 'codigo_iso_3' => 'AZE'],
            ['nombre' => 'Bangladés', 'codigo_iso_2' => 'BD', 'codigo_iso_3' => 'BGD'],
            ['nombre' => 'Baréin', 'codigo_iso_2' => 'BH', 'codigo_iso_3' => 'BHR'],
            ['nombre' => 'Birmania (Myanmar)', 'codigo_iso_2' => 'MM', 'codigo_iso_3' => 'MMR'],
            ['nombre' => 'Brunéi', 'codigo_iso_2' => 'BN', 'codigo_iso_3' => 'BRN'],
            ['nombre' => 'Bután', 'codigo_iso_2' => 'BT', 'codigo_iso_3' => 'BTN'],
            ['nombre' => 'Camboya', 'codigo_iso_2' => 'KH', 'codigo_iso_3' => 'KHM'],
            ['nombre' => 'Catar', 'codigo_iso_2' => 'QA', 'codigo_iso_3' => 'QAT'],
            ['nombre' => 'China', 'codigo_iso_2' => 'CN', 'codigo_iso_3' => 'CHN'],
            ['nombre' => 'Chipre', 'codigo_iso_2' => 'CY', 'codigo_iso_3' => 'CYP'],
            ['nombre' => 'Corea del Norte', 'codigo_iso_2' => 'KP', 'codigo_iso_3' => 'PRK'],
            ['nombre' => 'Corea del Sur', 'codigo_iso_2' => 'KR', 'codigo_iso_3' => 'KOR'],
            ['nombre' => 'Emiratos Árabes Unidos', 'codigo_iso_2' => 'AE', 'codigo_iso_3' => 'ARE'],
            ['nombre' => 'Filipinas', 'codigo_iso_2' => 'PH', 'codigo_iso_3' => 'PHL'],
            ['nombre' => 'Georgia', 'codigo_iso_2' => 'GE', 'codigo_iso_3' => 'GEO'],
            ['nombre' => 'India', 'codigo_iso_2' => 'IN', 'codigo_iso_3' => 'IND'],
            ['nombre' => 'Indonesia', 'codigo_iso_2' => 'ID', 'codigo_iso_3' => 'IDN'],
            ['nombre' => 'Irak', 'codigo_iso_2' => 'IQ', 'codigo_iso_3' => 'IRQ'],
            ['nombre' => 'Irán', 'codigo_iso_2' => 'IR', 'codigo_iso_3' => 'IRN'],
            ['nombre' => 'Israel', 'codigo_iso_2' => 'IL', 'codigo_iso_3' => 'ISR'],
            ['nombre' => 'Japón', 'codigo_iso_2' => 'JP', 'codigo_iso_3' => 'JPN'],
            ['nombre' => 'Jordania', 'codigo_iso_2' => 'JO', 'codigo_iso_3' => 'JOR'],
            ['nombre' => 'Kazajistán', 'codigo_iso_2' => 'KZ', 'codigo_iso_3' => 'KAZ'],
            ['nombre' => 'Kirguistán', 'codigo_iso_2' => 'KG', 'codigo_iso_3' => 'KGZ'],
            ['nombre' => 'Kuwait', 'codigo_iso_2' => 'KW', 'codigo_iso_3' => 'KWT'],
            ['nombre' => 'Laos', 'codigo_iso_2' => 'LA', 'codigo_iso_3' => 'LAO'],
            ['nombre' => 'Líbano', 'codigo_iso_2' => 'LB', 'codigo_iso_3' => 'LBN'],
            ['nombre' => 'Malasia', 'codigo_iso_2' => 'MY', 'codigo_iso_3' => 'MYS'],
            ['nombre' => 'Maldivas', 'codigo_iso_2' => 'MV', 'codigo_iso_3' => 'MDV'],
            ['nombre' => 'Mongolia', 'codigo_iso_2' => 'MN', 'codigo_iso_3' => 'MNG'],
            ['nombre' => 'Nepal', 'codigo_iso_2' => 'NP', 'codigo_iso_3' => 'NPL'],
            ['nombre' => 'Omán', 'codigo_iso_2' => 'OM', 'codigo_iso_3' => 'OMN'],
            ['nombre' => 'Pakistán', 'codigo_iso_2' => 'PK', 'codigo_iso_3' => 'PAK'],
            ['nombre' => 'Rusia', 'codigo_iso_2' => 'RU', 'codigo_iso_3' => 'RUS'],
            ['nombre' => 'Singapur', 'codigo_iso_2' => 'SG', 'codigo_iso_3' => 'SGP'],
            ['nombre' => 'Siria', 'codigo_iso_2' => 'SY', 'codigo_iso_3' => 'SYR'],
            ['nombre' => 'Sri Lanka', 'codigo_iso_2' => 'LK', 'codigo_iso_3' => 'LKA'],
            ['nombre' => 'Tailandia', 'codigo_iso_2' => 'TH', 'codigo_iso_3' => 'THA'],
            ['nombre' => 'Taiwán', 'codigo_iso_2' => 'TW', 'codigo_iso_3' => 'TWN'],
            ['nombre' => 'Tayikistán', 'codigo_iso_2' => 'TJ', 'codigo_iso_3' => 'TJK'],
            ['nombre' => 'Timor Oriental', 'codigo_iso_2' => 'TL', 'codigo_iso_3' => 'TLS'],
            ['nombre' => 'Turkmenistán', 'codigo_iso_2' => 'TM', 'codigo_iso_3' => 'TKM'],
            ['nombre' => 'Turquía', 'codigo_iso_2' => 'TR', 'codigo_iso_3' => 'TUR'],
            ['nombre' => 'Uzbekistán', 'codigo_iso_2' => 'UZ', 'codigo_iso_3' => 'UZB'],
            ['nombre' => 'Vietnam', 'codigo_iso_2' => 'VN', 'codigo_iso_3' => 'VNM'],
            ['nombre' => 'Yemen', 'codigo_iso_2' => 'YE', 'codigo_iso_3' => 'YEM'],

            // 🌎 América (35)
            ['nombre' => 'Antigua y Barbuda', 'codigo_iso_2' => 'AG', 'codigo_iso_3' => 'ATG'],
            ['nombre' => 'Argentina', 'codigo_iso_2' => 'AR', 'codigo_iso_3' => 'ARG'],
            ['nombre' => 'Bahamas', 'codigo_iso_2' => 'BS', 'codigo_iso_3' => 'BHS'],
            ['nombre' => 'Barbados', 'codigo_iso_2' => 'BB', 'codigo_iso_3' => 'BRB'],
            ['nombre' => 'Belice', 'codigo_iso_2' => 'BZ', 'codigo_iso_3' => 'BLZ'],
            ['nombre' => 'Bolivia', 'codigo_iso_2' => 'BO', 'codigo_iso_3' => 'BOL'],
            ['nombre' => 'Brasil', 'codigo_iso_2' => 'BR', 'codigo_iso_3' => 'BRA'],
            ['nombre' => 'Canadá', 'codigo_iso_2' => 'CA', 'codigo_iso_3' => 'CAN'],
            ['nombre' => 'Chile', 'codigo_iso_2' => 'CL', 'codigo_iso_3' => 'CHL'],
            ['nombre' => 'Colombia', 'codigo_iso_2' => 'CO', 'codigo_iso_3' => 'COL'],
            ['nombre' => 'Costa Rica', 'codigo_iso_2' => 'CR', 'codigo_iso_3' => 'CRI'],
            ['nombre' => 'Cuba', 'codigo_iso_2' => 'CU', 'codigo_iso_3' => 'CUB'],
            ['nombre' => 'Dominica', 'codigo_iso_2' => 'DM', 'codigo_iso_3' => 'DMA'],
            ['nombre' => 'Ecuador', 'codigo_iso_2' => 'EC', 'codigo_iso_3' => 'ECU'],
            ['nombre' => 'El Salvador', 'codigo_iso_2' => 'SV', 'codigo_iso_3' => 'SLV'],
            ['nombre' => 'Estados Unidos', 'codigo_iso_2' => 'US', 'codigo_iso_3' => 'USA'],
            ['nombre' => 'Granada', 'codigo_iso_2' => 'GD', 'codigo_iso_3' => 'GRD'],
            ['nombre' => 'Guatemala', 'codigo_iso_2' => 'GT', 'codigo_iso_3' => 'GTM'],
            ['nombre' => 'Guyana', 'codigo_iso_2' => 'GY', 'codigo_iso_3' => 'GUY'],
            ['nombre' => 'Haití', 'codigo_iso_2' => 'HT', 'codigo_iso_3' => 'HTI'],
            ['nombre' => 'Honduras', 'codigo_iso_2' => 'HN', 'codigo_iso_3' => 'HND'],
            ['nombre' => 'Jamaica', 'codigo_iso_2' => 'JM', 'codigo_iso_3' => 'JAM'],
            ['nombre' => 'México', 'codigo_iso_2' => 'MX', 'codigo_iso_3' => 'MEX'],
            ['nombre' => 'Nicaragua', 'codigo_iso_2' => 'NI', 'codigo_iso_3' => 'NIC'],
            ['nombre' => 'Panamá', 'codigo_iso_2' => 'PA', 'codigo_iso_3' => 'PAN'],
            ['nombre' => 'Paraguay', 'codigo_iso_2' => 'PY', 'codigo_iso_3' => 'PRY'],
            ['nombre' => 'Perú', 'codigo_iso_2' => 'PE', 'codigo_iso_3' => 'PER'],
            ['nombre' => 'República Dominicana', 'codigo_iso_2' => 'DO', 'codigo_iso_3' => 'DOM'],
            ['nombre' => 'San Cristóbal y Nieves', 'codigo_iso_2' => 'KN', 'codigo_iso_3' => 'KNA'],
            ['nombre' => 'San Vicente y las Granadinas', 'codigo_iso_2' => 'VC', 'codigo_iso_3' => 'VCT'],
            ['nombre' => 'Santa Lucía', 'codigo_iso_2' => 'LC', 'codigo_iso_3' => 'LCA'],
            ['nombre' => 'Surinam', 'codigo_iso_2' => 'SR', 'codigo_iso_3' => 'SUR'],
            ['nombre' => 'Trinidad y Tobago', 'codigo_iso_2' => 'TT', 'codigo_iso_3' => 'TTO'],
            ['nombre' => 'Uruguay', 'codigo_iso_2' => 'UY', 'codigo_iso_3' => 'URY'],
            ['nombre' => 'Venezuela', 'codigo_iso_2' => 'VE', 'codigo_iso_3' => 'VEN'],

            // 🌏 Oceanía (14)
            ['nombre' => 'Australia', 'codigo_iso_2' => 'AU', 'codigo_iso_3' => 'AUS'],
            ['nombre' => 'Fiyi', 'codigo_iso_2' => 'FJ', 'codigo_iso_3' => 'FJI'],
            ['nombre' => 'Islas Marshall', 'codigo_iso_2' => 'MH', 'codigo_iso_3' => 'MHL'],
            ['nombre' => 'Islas Salomón', 'codigo_iso_2' => 'SB', 'codigo_iso_3' => 'SLB'],
            ['nombre' => 'Kiribati', 'codigo_iso_2' => 'KI', 'codigo_iso_3' => 'KIR'],
            ['nombre' => 'Micronesia', 'codigo_iso_2' => 'FM', 'codigo_iso_3' => 'FSM'],
            ['nombre' => 'Nauru', 'codigo_iso_2' => 'NR', 'codigo_iso_3' => 'NRU'],
            ['nombre' => 'Nueva Zelanda', 'codigo_iso_2' => 'NZ', 'codigo_iso_3' => 'NZL'],
            ['nombre' => 'Palaos', 'codigo_iso_2' => 'PW', 'codigo_iso_3' => 'PLW'],
            ['nombre' => 'Papúa Nueva Guinea', 'codigo_iso_2' => 'PG', 'codigo_iso_3' => 'PNG'],
            ['nombre' => 'Samoa', 'codigo_iso_2' => 'WS', 'codigo_iso_3' => 'WSM'],
            ['nombre' => 'Tonga', 'codigo_iso_2' => 'TO', 'codigo_iso_3' => 'TON'],
            ['nombre' => 'Tuvalu', 'codigo_iso_2' => 'TV', 'codigo_iso_3' => 'TUV'],
            ['nombre' => 'Vanuatu', 'codigo_iso_2' => 'VU', 'codigo_iso_3' => 'VUT'],

            // 🌍 Europa (44)
            ['nombre' => 'Albania', 'codigo_iso_2' => 'AL', 'codigo_iso_3' => 'ALB'],
            ['nombre' => 'Alemania', 'codigo_iso_2' => 'DE', 'codigo_iso_3' => 'DEU'],
            ['nombre' => 'Andorra', 'codigo_iso_2' => 'AD', 'codigo_iso_3' => 'AND'],
            ['nombre' => 'Austria', 'codigo_iso_2' => 'AT', 'codigo_iso_3' => 'AUT'],
            ['nombre' => 'Bélgica', 'codigo_iso_2' => 'BE', 'codigo_iso_3' => 'BEL'],
            ['nombre' => 'Bielorrusia', 'codigo_iso_2' => 'BY', 'codigo_iso_3' => 'BLR'],
            ['nombre' => 'Bosnia y Herzegovina', 'codigo_iso_2' => 'BA', 'codigo_iso_3' => 'BIH'],
            ['nombre' => 'Bulgaria', 'codigo_iso_2' => 'BG', 'codigo_iso_3' => 'BGR'],
            ['nombre' => 'Ciudad del Vaticano', 'codigo_iso_2' => 'VA', 'codigo_iso_3' => 'VAT'],
            ['nombre' => 'Croacia', 'codigo_iso_2' => 'HR', 'codigo_iso_3' => 'HRV'],
            ['nombre' => 'Dinamarca', 'codigo_iso_2' => 'DK', 'codigo_iso_3' => 'DNK'],
            ['nombre' => 'Eslovaquia', 'codigo_iso_2' => 'SK', 'codigo_iso_3' => 'SVK'],
            ['nombre' => 'Eslovenia', 'codigo_iso_2' => 'SI', 'codigo_iso_3' => 'SVN'],
            ['nombre' => 'España', 'codigo_iso_2' => 'ES', 'codigo_iso_3' => 'ESP'],
            ['nombre' => 'Estonia', 'codigo_iso_2' => 'EE', 'codigo_iso_3' => 'EST'],
            ['nombre' => 'Finlandia', 'codigo_iso_2' => 'FI', 'codigo_iso_3' => 'FIN'],
            ['nombre' => 'Francia', 'codigo_iso_2' => 'FR', 'codigo_iso_3' => 'FRA'],
            ['nombre' => 'Grecia', 'codigo_iso_2' => 'GR', 'codigo_iso_3' => 'GRC'],
            ['nombre' => 'Hungría', 'codigo_iso_2' => 'HU', 'codigo_iso_3' => 'HUN'],
            ['nombre' => 'Irlanda', 'codigo_iso_2' => 'IE', 'codigo_iso_3' => 'IRL'],
            ['nombre' => 'Islandia', 'codigo_iso_2' => 'IS', 'codigo_iso_3' => 'ISL'],
            ['nombre' => 'Italia', 'codigo_iso_2' => 'IT', 'codigo_iso_3' => 'ITA'],
            ['nombre' => 'Kosovo', 'codigo_iso_2' => 'XK', 'codigo_iso_3' => 'XKX'],
            ['nombre' => 'Letonia', 'codigo_iso_2' => 'LV', 'codigo_iso_3' => 'LVA'],
            ['nombre' => 'Liechtenstein', 'codigo_iso_2' => 'LI', 'codigo_iso_3' => 'LIE'],
            ['nombre' => 'Lituania', 'codigo_iso_2' => 'LT', 'codigo_iso_3' => 'LTU'],
            ['nombre' => 'Luxemburgo', 'codigo_iso_2' => 'LU', 'codigo_iso_3' => 'LUX'],
            ['nombre' => 'Macedonia del Norte', 'codigo_iso_2' => 'MK', 'codigo_iso_3' => 'MKD'],
            ['nombre' => 'Malta', 'codigo_iso_2' => 'MT', 'codigo_iso_3' => 'MLT'],
            ['nombre' => 'Moldavia', 'codigo_iso_2' => 'MD', 'codigo_iso_3' => 'MDA'],
            ['nombre' => 'Mónaco', 'codigo_iso_2' => 'MC', 'codigo_iso_3' => 'MCO'],
            ['nombre' => 'Montenegro', 'codigo_iso_2' => 'ME', 'codigo_iso_3' => 'MNE'],
            ['nombre' => 'Noruega', 'codigo_iso_2' => 'NO', 'codigo_iso_3' => 'NOR'],
            ['nombre' => 'Países Bajos', 'codigo_iso_2' => 'NL', 'codigo_iso_3' => 'NLD'],
            ['nombre' => 'Polonia', 'codigo_iso_2' => 'PL', 'codigo_iso_3' => 'POL'],
            ['nombre' => 'Portugal', 'codigo_iso_2' => 'PT', 'codigo_iso_3' => 'PRT'],
            ['nombre' => 'Reino Unido', 'codigo_iso_2' => 'GB', 'codigo_iso_3' => 'GBR'],
            ['nombre' => 'República Checa', 'codigo_iso_2' => 'CZ', 'codigo_iso_3' => 'CZE'],
            ['nombre' => 'Rumanía', 'codigo_iso_2' => 'RO', 'codigo_iso_3' => 'ROU'],
            ['nombre' => 'San Marino', 'codigo_iso_2' => 'SM', 'codigo_iso_3' => 'SMR'],
            ['nombre' => 'Serbia', 'codigo_iso_2' => 'RS', 'codigo_iso_3' => 'SRB'],
            ['nombre' => 'Suecia', 'codigo_iso_2' => 'SE', 'codigo_iso_3' => 'SWE'],
            ['nombre' => 'Suiza', 'codigo_iso_2' => 'CH', 'codigo_iso_3' => 'CHE'],
            ['nombre' => 'Ucrania', 'codigo_iso_2' => 'UA', 'codigo_iso_3' => 'UKR'],

            // Observadores ONU (2)
            ['nombre' => 'Palestina', 'codigo_iso_2' => 'PS', 'codigo_iso_3' => 'PSE'],
        ];

        // Insertar todos los países
        DB::table('cli_paises')->insert($paises);
    }
}
